-- Backfill Postgres (legacy) bronze tables into ClickHouse bronze.
-- Update host/port/user/password if your legacy Postgres differs.

INSERT INTO bronze.wazuh_events_raw (
  event_id,
  event_ts,
  event_ingested_ts,
  event_start_ts,
  event_end_ts,
  event_dataset,
  event_kind,
  event_module,
  event_provider,
  agent_name,
  agent_ip,
  host_name,
  host_ip,
  rule_id,
  rule_level,
  rule_name,
  rule_ruleset,
  tags,
  message,
  raw_data
)
SELECT
  event_id,
  toTimeZone(parseDateTime64BestEffortOrNull(toString(event_ts)), 'Asia/Jakarta') AS event_ts,
  toTimeZone(parseDateTime64BestEffortOrNull(toString(event_ingested_ts)), 'Asia/Jakarta') AS event_ingested_ts,
  toTimeZone(parseDateTime64BestEffortOrNull(toString(event_start_ts)), 'Asia/Jakarta') AS event_start_ts,
  toTimeZone(parseDateTime64BestEffortOrNull(toString(event_end_ts)), 'Asia/Jakarta') AS event_end_ts,
  event_dataset,
  event_kind,
  event_module,
  event_provider,
  agent_name,
  toIPv6OrNull(toString(agent_ip)) AS agent_ip,
  host_name,
  toIPv6OrNull(toString(host_ip)) AS host_ip,
  rule_id,
  rule_level,
  rule_name,
  toString(rule_ruleset) AS rule_ruleset,
  JSONExtract(ifNull(toString(tags), '[]'), 'Array(String)') AS tags,
  message,
  ifNull(toString(raw_data), '') AS raw_data
FROM postgresql(
  'host.docker.internal:15433',
  'analytics',
  'wazuh_events_raw',
  'etl_runner',
  'etl_runner',
  'bronze'
);

INSERT INTO bronze.suricata_events_raw (
  event_id,
  event_ts,
  sensor_type,
  sensor_name,
  event_type,
  severity,
  src_ip,
  dest_ip,
  src_port,
  dest_port,
  protocol,
  bytes,
  packets,
  flow_id,
  signature,
  signature_id,
  category,
  alert_action,
  http_url,
  tags,
  message,
  raw_data
)
SELECT
  event_id,
  toTimeZone(parseDateTime64BestEffortOrNull(toString(event_ts)), 'Asia/Jakarta') AS event_ts,
  sensor_type,
  sensor_name,
  event_type,
  severity,
  toIPv6OrNull(toString(src_ip)) AS src_ip,
  toIPv6OrNull(toString(dest_ip)) AS dest_ip,
  src_port,
  dest_port,
  protocol,
  bytes,
  packets,
  flow_id,
  signature,
  signature_id,
  category,
  alert_action,
  http_url,
  JSONExtract(ifNull(toString(tags), '[]'), 'Array(String)') AS tags,
  message,
  ifNull(toString(raw_data), '') AS raw_data
FROM postgresql(
  'host.docker.internal:15433',
  'analytics',
  'suricata_events_raw',
  'etl_runner',
  'etl_runner',
  'bronze'
);

INSERT INTO bronze.zeek_events_raw (
  event_id,
  event_ts,
  event_ingested_ts,
  event_start_ts,
  event_end_ts,
  event_dataset,
  event_kind,
  event_module,
  event_provider,
  zeek_uid,
  sensor_name,
  src_ip,
  dest_ip,
  src_port,
  dest_port,
  protocol,
  application,
  network_type,
  direction,
  community_id,
  bytes,
  packets,
  orig_bytes,
  resp_bytes,
  orig_pkts,
  resp_pkts,
  conn_state,
  conn_state_description,
  duration,
  history,
  vlan_id,
  tags,
  message,
  raw_data
)
SELECT
  event_id,
  toTimeZone(parseDateTime64BestEffortOrNull(toString(event_ts)), 'Asia/Jakarta') AS event_ts,
  toTimeZone(parseDateTime64BestEffortOrNull(toString(event_ingested_ts)), 'Asia/Jakarta') AS event_ingested_ts,
  toTimeZone(parseDateTime64BestEffortOrNull(toString(event_start_ts)), 'Asia/Jakarta') AS event_start_ts,
  toTimeZone(parseDateTime64BestEffortOrNull(toString(event_end_ts)), 'Asia/Jakarta') AS event_end_ts,
  event_dataset,
  event_kind,
  event_module,
  event_provider,
  zeek_uid,
  sensor_name,
  toIPv6OrNull(toString(src_ip)) AS src_ip,
  toIPv6OrNull(toString(dest_ip)) AS dest_ip,
  src_port,
  dest_port,
  protocol,
  application,
  network_type,
  direction,
  community_id,
  bytes,
  packets,
  orig_bytes,
  resp_bytes,
  orig_pkts,
  resp_pkts,
  conn_state,
  conn_state_description,
  duration,
  history,
  vlan_id,
  JSONExtract(ifNull(toString(tags), '[]'), 'Array(String)') AS tags,
  message,
  ifNull(toString(raw_data), '') AS raw_data
FROM postgresql(
  'host.docker.internal:15433',
  'analytics',
  'zeek_events_raw',
  'etl_runner',
  'etl_runner',
  'bronze'
);
