-- Roles (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'rw_writer') THEN
    CREATE ROLE rw_writer LOGIN PASSWORD 'rw_writer';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'etl_runner') THEN
    CREATE ROLE etl_runner LOGIN PASSWORD 'etl_runner';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'bi_reader') THEN
    CREATE ROLE bi_reader LOGIN PASSWORD 'bi_reader';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'airflow') THEN
    CREATE ROLE airflow LOGIN PASSWORD 'airflow';
  END IF;
END
$$;

-- Databases
CREATE DATABASE airflow OWNER airflow;
GRANT CONNECT ON DATABASE analytics TO rw_writer, etl_runner, bi_reader;

-- Schemas
CREATE SCHEMA IF NOT EXISTS bronze;
CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS gold;
CREATE SCHEMA IF NOT EXISTS control;
CREATE SCHEMA IF NOT EXISTS monitoring;

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA bronze FROM PUBLIC;
REVOKE ALL ON SCHEMA staging FROM PUBLIC;
REVOKE ALL ON SCHEMA silver FROM PUBLIC;
REVOKE ALL ON SCHEMA gold FROM PUBLIC;
REVOKE ALL ON SCHEMA control FROM PUBLIC;
REVOKE ALL ON SCHEMA monitoring FROM PUBLIC;

-- Schema usage
GRANT USAGE ON SCHEMA bronze TO rw_writer, etl_runner;
GRANT USAGE ON SCHEMA staging TO rw_writer, etl_runner;
GRANT USAGE ON SCHEMA silver TO etl_runner;
GRANT USAGE ON SCHEMA gold TO etl_runner, bi_reader;
GRANT USAGE ON SCHEMA control TO etl_runner;
GRANT USAGE ON SCHEMA monitoring TO etl_runner;

GRANT CREATE ON SCHEMA silver TO etl_runner;
GRANT CREATE ON SCHEMA gold TO etl_runner;
GRANT CREATE ON SCHEMA monitoring TO etl_runner;

-- Bronze: insert only for rw_writer
GRANT INSERT ON ALL TABLES IN SCHEMA bronze TO rw_writer;
ALTER DEFAULT PRIVILEGES IN SCHEMA bronze GRANT INSERT ON TABLES TO rw_writer;

-- Staging: insert/select for rw_writer (backfill landing)
GRANT INSERT ON ALL TABLES IN SCHEMA staging TO rw_writer;
ALTER DEFAULT PRIVILEGES IN SCHEMA staging GRANT INSERT ON TABLES TO rw_writer;
GRANT SELECT ON ALL TABLES IN SCHEMA staging TO rw_writer, etl_runner;
ALTER DEFAULT PRIVILEGES IN SCHEMA staging GRANT SELECT ON TABLES TO rw_writer;
ALTER DEFAULT PRIVILEGES IN SCHEMA staging GRANT SELECT ON TABLES TO etl_runner;

-- Bronze: read for etl_runner
GRANT SELECT ON ALL TABLES IN SCHEMA bronze TO etl_runner;
ALTER DEFAULT PRIVILEGES IN SCHEMA bronze GRANT SELECT ON TABLES TO etl_runner;

-- Silver/Gold/Monitoring: full DML for etl_runner
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA silver TO etl_runner;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA gold TO etl_runner;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA monitoring TO etl_runner;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA silver TO etl_runner;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA gold TO etl_runner;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA monitoring TO etl_runner;
ALTER DEFAULT PRIVILEGES IN SCHEMA silver GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO etl_runner;
ALTER DEFAULT PRIVILEGES IN SCHEMA gold GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO etl_runner;
ALTER DEFAULT PRIVILEGES IN SCHEMA monitoring GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO etl_runner;
ALTER DEFAULT PRIVILEGES IN SCHEMA silver GRANT USAGE, SELECT ON SEQUENCES TO etl_runner;
ALTER DEFAULT PRIVILEGES IN SCHEMA gold GRANT USAGE, SELECT ON SEQUENCES TO etl_runner;
ALTER DEFAULT PRIVILEGES IN SCHEMA monitoring GRANT USAGE, SELECT ON SEQUENCES TO etl_runner;

-- Control: read only for etl_runner
GRANT SELECT ON ALL TABLES IN SCHEMA control TO etl_runner;
ALTER DEFAULT PRIVILEGES IN SCHEMA control GRANT SELECT ON TABLES TO etl_runner;

-- BI reader: select only on gold
GRANT SELECT ON ALL TABLES IN SCHEMA gold TO bi_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA gold GRANT SELECT ON TABLES TO bi_reader;

-- Objects created by etl_runner also grant read on gold to bi_reader
ALTER DEFAULT PRIVILEGES FOR ROLE etl_runner IN SCHEMA gold GRANT SELECT ON TABLES TO bi_reader;
