-- Gold star schema: dimensions, facts, and bridges
-- Fact tables are range-partitioned by event_ts (daily).

CREATE TABLE IF NOT EXISTS gold.dim_date (
  date_key int PRIMARY KEY,
  date date NOT NULL,
  year int NOT NULL,
  quarter int NOT NULL,
  month int NOT NULL,
  day int NOT NULL,
  week_of_year int NOT NULL,
  day_of_week int NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_dim_date_date ON gold.dim_date (date);

CREATE TABLE IF NOT EXISTS gold.dim_time (
  time_key int PRIMARY KEY,
  hour int NOT NULL,
  minute int NOT NULL,
  second int NOT NULL
);

CREATE TABLE IF NOT EXISTS gold.dim_host (
  host_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  host_name text,
  host_ip inet,
  effective_from timestamptz NOT NULL DEFAULT now(),
  effective_to timestamptz,
  is_current boolean NOT NULL DEFAULT true
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_dim_host_current
  ON gold.dim_host (host_name, host_ip)
  WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_dim_host_natural
  ON gold.dim_host (host_name, host_ip);

CREATE TABLE IF NOT EXISTS gold.dim_tag (
  tag_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag_value text NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_dim_tag_value ON gold.dim_tag (tag_value);

CREATE TABLE IF NOT EXISTS gold.dim_agent (
  agent_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_name text,
  agent_ip inet,
  effective_from timestamptz NOT NULL DEFAULT now(),
  effective_to timestamptz,
  is_current boolean NOT NULL DEFAULT true
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_dim_agent_current
  ON gold.dim_agent (agent_name, agent_ip)
  WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_dim_agent_natural
  ON gold.dim_agent (agent_name, agent_ip);

CREATE TABLE IF NOT EXISTS gold.dim_rule (
  rule_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_id text,
  rule_level int,
  rule_name text,
  rule_ruleset jsonb,
  effective_from timestamptz NOT NULL DEFAULT now(),
  effective_to timestamptz,
  is_current boolean NOT NULL DEFAULT true
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_dim_rule_current
  ON gold.dim_rule (rule_id)
  WHERE is_current AND rule_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_dim_rule_id ON gold.dim_rule (rule_id);

CREATE TABLE IF NOT EXISTS gold.dim_event (
  event_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_dataset text,
  event_kind text,
  event_module text,
  event_provider text
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_dim_event_natural
  ON gold.dim_event (event_dataset, event_kind, event_module, event_provider);

CREATE TABLE IF NOT EXISTS gold.dim_sensor (
  sensor_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sensor_type text,
  sensor_name text
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_dim_sensor_natural
  ON gold.dim_sensor (sensor_type, sensor_name);

CREATE TABLE IF NOT EXISTS gold.dim_signature (
  signature_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  signature_id int,
  signature text,
  category text,
  alert_action text
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_dim_signature_id
  ON gold.dim_signature (signature_id)
  WHERE signature_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS gold.dim_protocol (
  protocol_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  protocol text NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_dim_protocol_value ON gold.dim_protocol (protocol);

CREATE TABLE IF NOT EXISTS gold.fact_wazuh_events (
  event_id text NOT NULL,
  event_ts timestamptz NOT NULL,
  event_ingested_ts timestamptz,
  event_start_ts timestamptz,
  event_end_ts timestamptz,
  date_key int REFERENCES gold.dim_date (date_key),
  time_key int REFERENCES gold.dim_time (time_key),
  agent_key bigint REFERENCES gold.dim_agent (agent_key),
  host_key bigint REFERENCES gold.dim_host (host_key),
  rule_key bigint REFERENCES gold.dim_rule (rule_key),
  event_key bigint REFERENCES gold.dim_event (event_key),
  lag_seconds double precision,
  duration_seconds double precision,
  message text,
  PRIMARY KEY (event_id, event_ts)
) PARTITION BY RANGE (event_ts);

CREATE INDEX IF NOT EXISTS idx_fact_wazuh_event_ts ON gold.fact_wazuh_events (event_ts);
CREATE INDEX IF NOT EXISTS idx_fact_wazuh_rule_key ON gold.fact_wazuh_events (rule_key);
CREATE INDEX IF NOT EXISTS idx_fact_wazuh_agent_key ON gold.fact_wazuh_events (agent_key);
CREATE INDEX IF NOT EXISTS idx_fact_wazuh_host_key ON gold.fact_wazuh_events (host_key);

CREATE TABLE IF NOT EXISTS gold.fact_suricata_events (
  event_id text NOT NULL,
  event_ts timestamptz NOT NULL,
  date_key int REFERENCES gold.dim_date (date_key),
  time_key int REFERENCES gold.dim_time (time_key),
  sensor_key bigint REFERENCES gold.dim_sensor (sensor_key),
  signature_key bigint REFERENCES gold.dim_signature (signature_key),
  protocol_key bigint REFERENCES gold.dim_protocol (protocol_key),
  event_type text,
  severity text,
  src_ip inet,
  dest_ip inet,
  src_port int,
  dest_port int,
  bytes bigint,
  packets bigint,
  flow_id text,
  http_url text,
  message text,
  PRIMARY KEY (event_id, event_ts)
) PARTITION BY RANGE (event_ts);

CREATE INDEX IF NOT EXISTS idx_fact_suricata_event_ts ON gold.fact_suricata_events (event_ts);
CREATE INDEX IF NOT EXISTS idx_fact_suricata_signature_key ON gold.fact_suricata_events (signature_key);
CREATE INDEX IF NOT EXISTS idx_fact_suricata_sensor_key ON gold.fact_suricata_events (sensor_key);
CREATE INDEX IF NOT EXISTS idx_fact_suricata_protocol_key ON gold.fact_suricata_events (protocol_key);

CREATE TABLE IF NOT EXISTS gold.fact_zeek_events (
  event_id text NOT NULL,
  event_ts timestamptz NOT NULL,
  event_ingested_ts timestamptz,
  event_start_ts timestamptz,
  event_end_ts timestamptz,
  date_key int REFERENCES gold.dim_date (date_key),
  time_key int REFERENCES gold.dim_time (time_key),
  sensor_key bigint REFERENCES gold.dim_sensor (sensor_key),
  protocol_key bigint REFERENCES gold.dim_protocol (protocol_key),
  event_key bigint REFERENCES gold.dim_event (event_key),
  zeek_uid text,
  src_ip inet,
  dest_ip inet,
  src_port int,
  dest_port int,
  application text,
  network_type text,
  direction text,
  community_id text,
  bytes bigint,
  packets bigint,
  orig_bytes bigint,
  resp_bytes bigint,
  orig_pkts bigint,
  resp_pkts bigint,
  conn_state text,
  conn_state_description text,
  duration_seconds double precision,
  history text,
  vlan_id text,
  message text,
  PRIMARY KEY (event_id, event_ts)
) PARTITION BY RANGE (event_ts);

CREATE INDEX IF NOT EXISTS idx_fact_zeek_event_ts ON gold.fact_zeek_events (event_ts);
CREATE INDEX IF NOT EXISTS idx_fact_zeek_sensor_key ON gold.fact_zeek_events (sensor_key);
CREATE INDEX IF NOT EXISTS idx_fact_zeek_protocol_key ON gold.fact_zeek_events (protocol_key);
CREATE INDEX IF NOT EXISTS idx_fact_zeek_event_key ON gold.fact_zeek_events (event_key);

CREATE OR REPLACE FUNCTION gold.create_daily_fact_partitions(start_date date, end_date date)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
  d date;
  next_date date;
BEGIN
  IF end_date <= start_date THEN
    RAISE EXCEPTION 'end_date must be greater than start_date';
  END IF;

  d := start_date;
  WHILE d < end_date LOOP
    next_date := d + 1;

    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS gold.fact_wazuh_events_p%s PARTITION OF gold.fact_wazuh_events FOR VALUES FROM (%L) TO (%L);',
      to_char(d, 'YYYYMMDD'), d, next_date
    );
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS gold.fact_suricata_events_p%s PARTITION OF gold.fact_suricata_events FOR VALUES FROM (%L) TO (%L);',
      to_char(d, 'YYYYMMDD'), d, next_date
    );
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS gold.fact_zeek_events_p%s PARTITION OF gold.fact_zeek_events FOR VALUES FROM (%L) TO (%L);',
      to_char(d, 'YYYYMMDD'), d, next_date
    );

    d := next_date;
  END LOOP;
END;
$$;

-- Create partitions around the current date. Adjust or schedule as needed.
SELECT gold.create_daily_fact_partitions(current_date - 7, current_date + 30);

CREATE TABLE IF NOT EXISTS gold.bridge_wazuh_event_tag (
  event_id text NOT NULL,
  event_ts timestamptz NOT NULL,
  tag_key bigint NOT NULL REFERENCES gold.dim_tag (tag_key),
  PRIMARY KEY (event_id, event_ts, tag_key),
  FOREIGN KEY (event_id, event_ts)
    REFERENCES gold.fact_wazuh_events (event_id, event_ts)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_bridge_wazuh_tag_key ON gold.bridge_wazuh_event_tag (tag_key);

CREATE TABLE IF NOT EXISTS gold.bridge_suricata_event_tag (
  event_id text NOT NULL,
  event_ts timestamptz NOT NULL,
  tag_key bigint NOT NULL REFERENCES gold.dim_tag (tag_key),
  PRIMARY KEY (event_id, event_ts, tag_key),
  FOREIGN KEY (event_id, event_ts)
    REFERENCES gold.fact_suricata_events (event_id, event_ts)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_bridge_suricata_tag_key ON gold.bridge_suricata_event_tag (tag_key);

CREATE TABLE IF NOT EXISTS gold.bridge_zeek_event_tag (
  event_id text NOT NULL,
  event_ts timestamptz NOT NULL,
  tag_key bigint NOT NULL REFERENCES gold.dim_tag (tag_key),
  PRIMARY KEY (event_id, event_ts, tag_key),
  FOREIGN KEY (event_id, event_ts)
    REFERENCES gold.fact_zeek_events (event_id, event_ts)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_bridge_zeek_tag_key ON gold.bridge_zeek_event_tag (tag_key);

-- Ensure privileges for gold objects created at init time.
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA gold TO etl_runner;
GRANT SELECT ON ALL TABLES IN SCHEMA gold TO bi_reader;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA gold TO etl_runner;